import { useQueryClient } from '@tanstack/react-query';
import { useRouter } from 'expo-router';
import React from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import * as api from '../src/api';
import { keys, useNotifications } from '../src/api/hooks';
import { NotificationKind, NotificationRow } from '../src/api/types';
import { Check, Inbox, MessageSquare, Star } from '../src/components/icons';
import { HeaderRow, Screen } from '../src/components/Layout';
import { BORDER, colors, fonts, s, TAB_PAD } from '../src/theme/tokens';
import { type as t } from '../src/theme/typography';
import { isToday, timeAgo } from '../src/utils/time';

const LOOK: Record<NotificationKind, { bg: string; icon: React.ReactNode }> = {
  request: { bg: colors.blueSoft, icon: <Inbox size={s(20)} color={colors.blue} strokeWidth={2.1} /> },
  approved: { bg: colors.tealSoft, icon: <Check size={s(20)} color={colors.teal} strokeWidth={2.6} /> },
  badge: { bg: colors.yellowSoft, icon: <Star size={s(20)} color={colors.yellow} strokeWidth={2} /> },
  message: { bg: colors.orangeSoft, icon: <MessageSquare size={s(19)} color={colors.peachIcon} strokeWidth={2.1} /> },
};

function Line({ n }: { n: NotificationRow }) {
  const name = n.actor_name || 'A member';
  switch (n.kind) {
    case 'request':
      return (<><Text style={styles.bold}>{name}</Text> sent you a connect request</>);
    case 'approved':
      return (<><Text style={styles.bold}>{name}</Text> approved your request</>);
    case 'message':
      return (<><Text style={styles.bold}>{name}</Text> sent you a message</>);
    default:
      return (<>Your profile got a <Text style={styles.bold}>verified badge</Text></>);
  }
}

/** 26 · Notifications (server-generated by database triggers). */
export default function Notifications() {
  const router = useRouter();
  const qc = useQueryClient();
  const { data = [], isLoading } = useNotifications();

  const open = async (n: NotificationRow) => {
    if (!n.read_at) {
      api.notifications.markRead(n.id).then(() => qc.invalidateQueries({ queryKey: keys.notifications })).catch(() => {});
    }
    if (n.kind === 'request') router.navigate('/requests');
    else if (n.connection_id) router.push(`/chat/${n.connection_id}`);
    else if (n.kind === 'badge') router.push('/settings');
  };

  const section = (label: string, items: NotificationRow[]) =>
    items.length ? (
      <View>
        <Text style={[t.sectionLabel, styles.section]}>{label}</Text>
        {items.map((n) => (
          <Pressable key={n.id} onPress={() => open(n)} style={({ pressed }) => [styles.card, pressed && { opacity: 0.8 }]}>
            <View style={[styles.icon, { backgroundColor: LOOK[n.kind].bg }]}>{LOOK[n.kind].icon}</View>
            <View style={{ flex: 1, marginLeft: s(14) }}>
              <Text style={styles.text}>
                <Line n={n} />
              </Text>
              <Text style={styles.time}>{timeAgo(n.created_at)}</Text>
            </View>
            {!n.read_at && <View style={styles.dot} />}
          </Pressable>
        ))}
      </View>
    ) : null;

  return (
    <Screen>
      <HeaderRow title="Notifications" style={{ paddingHorizontal: TAB_PAD }} />
      <ScrollView contentContainerStyle={{ paddingHorizontal: TAB_PAD, paddingBottom: s(30) }}>
        {isLoading && <ActivityIndicator style={{ marginTop: s(30) }} color={colors.blue} />}
        {section('TODAY', data.filter((n) => isToday(n.created_at)))}
        {section('EARLIER', data.filter((n) => !isToday(n.created_at)))}
        {!isLoading && data.length === 0 && (
          <Text style={[t.bodyInk, { textAlign: 'center', marginTop: s(40) }]}>You're all caught up.</Text>
        )}
      </ScrollView>
    </Screen>
  );
}

const styles = StyleSheet.create({
  section: { marginTop: s(24), marginBottom: s(12), marginLeft: s(4) },
  card: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    borderRadius: s(26),
    borderWidth: BORDER,
    borderColor: colors.ink,
    backgroundColor: colors.white,
    padding: s(16),
    marginBottom: s(12),
  },
  icon: { width: s(42), height: s(42), borderRadius: s(12), alignItems: 'center', justifyContent: 'center' },
  text: { fontFamily: fonts.bodyMedium, fontSize: s(16.5), lineHeight: s(23), color: colors.ink },
  bold: { fontFamily: fonts.bodyBold },
  time: { fontFamily: fonts.body, fontSize: s(14.5), color: colors.textMuted, marginTop: s(2) },
  dot: { width: s(10), height: s(10), borderRadius: s(5), backgroundColor: colors.alert, marginLeft: s(8), marginTop: s(4) },
});
